#pragma once

typedef enum {
	MAYBE_ERROR_UNINITIALIZED,
	MAYBE_ERROR_SUCCESS,

	MAYBE_ERROR_LOGGER_FORMAT_FAILED,
	MAYBE_ERROR_LOGGER_CONSOLE_ERROR,
	MAYBE_ERROR_LOGGER_FILE_ERROR,
	MAYBE_ERROR_LOGGER_FILE_INVALID_FILE_NAME,
	MAYBE_ERROR_LOGGER_FILE_WRITE_FAILED,
	
	MAYBE_ERROR_LIST_NULL_PARAM,
	MAYBE_ERROR_LIST_ALLOCATION_FAILED,

	MAYBE_ERROR_MAP_NULL_PARAM,
	MAYBE_ERROR_MAP_ALLOCATION_FAILED,

	MAYBE_ERROR_VECTOR_NULL_PARAM,
	MAYBE_ERROR_VECTOR_ALLOCATION_FAILED,
	MAYBE_ERROR_VECTOR_INDEX_OUT_OF_RANGE,
	
	MAYBE_ERROR_ARCHETYPE_NULL_PARAM,
	MAYBE_ERROR_ARCHETYPE_ALLOCATION_FAILED,

	MAYBE_ERROR_ECS_WORLD_NULL_PARAM,
	MAYBE_ERROR_ECS_WORLD_ALLOCATION_FAILED,

	MAYBE_ERROR_SYSTEM_NULL_PARAM,
	MAYBE_ERROR_SYSTEM_ALLOCATION_FAILED,
	MAYBE_ERROR_SYSTEM_BAD_ARCHETYPE,
	MAYBE_ERROR_SYSTEM_COMPONENT_ITERATOR_LAST_COMPONENT_REACHED
} maybe_error_t;
